project:
  type: website
  output-dir: docs

website:
  title: "Joel Riphagen"
  site-url: "https://joelrip.github.io"
  favicon: images/RClogoOnly.png
  navbar:
    title: Joel Riphagen
    logo: images/RClogoWhiteBorder.png
    right:
      - href: index.qmd
        text: home
      - about.qmd
      - posts.qmd
  page-footer: 
    background: light
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/joelriphagen/
        aria-label: "LinkedIn"
      - icon: twitter
        href: https://twitter.com/joelrip
        aria-label: "Twitter"
      - icon: github
        href: https://github.com/joelrip
        aria-label: "Github"
      - icon: envelope-fill
        href: mailto:joelrip@gmail.com
        aria-label: "Email me"
      - icon: rss
        href: posts.xml
        aria-label: "RSS feed"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



