project:
  type: website
  output-dir: docs

website:
  title: "Joel Riphagen"
  site-url: "https://joelriphagen.net"
  description: "Explorations in data and policy from Sacramento, CA"
  favicon: images/RClogoOnly.png
  navbar:
    title: Joel Riphagen
    logo: images/RClogoWhiteBorder.png
    right:
      - href: index.qmd
        text: home
      - href: about.qmd
        text: resume
      - href: posts.qmd
        text: blog
      - href: projects.qmd
        text: projects
  page-footer: 
    background: light
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/joelriphagen/
        aria-label: "LinkedIn"
      - icon: twitter
        href: https://twitter.com/joelrip
        aria-label: "Twitter"
      - icon: github
        href: https://github.com/joelrip
        aria-label: "Github"
      - icon: envelope-fill
        href: mailto:joelrip@gmail.com
        aria-label: "Email me"
      - icon: rss
        href: posts.xml
        aria-label: "RSS feed"

format:
  html:
    theme: flatly
#      - defaultstyle.scss
#      light: flatly
#      dark: darkly
    linkcolor: black
    css: styles.css
    toc: true


