project:
  type: website
  output-dir: docs

website:
  title: "Joel Riphagen"
  favicon: images/RClogoWhiteBorder.png
  navbar:
    title: false
    logo: images/RClogoWhiteBorder.png
    right:
      - href: index.qmd
        text: home
      - about.qmd
  page-footer: 
    background: light
    right: 
      - icon: github
        href: https://github.com/joelrip
        aria-label: Github
      - icon: twitter
        href: https://twitter.com/joelrip
        aria-label: Twitter

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



